apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blitzshare-ns
  name: blitzshare-event-worker-deployment
  labels:
    app: blitzshare-event-worker-app
spec:
  selector:
    matchLabels:
      app: blitzshare-event-worker-app
  replicas: 1
  template:
    metadata:
      labels:
        app: blitzshare-event-worker-app
    spec:
      containers:
        - name: blitzshare-event-worker-containter
          image: iamkimchi/blitzshare.event.worker:latest
          env:
            - name: QUEUE_URL
              value: kubemq-cluster-grpc.kubemq.svc.cluster.local
            - name: REDIS_URL
              value: "redis-svc.blitzshare-redis-ns.svc.cluster.local:6379"
          resources:
            limits:
              memory: 256Mi
              cpu: "250m"
            requests:
              memory: 128Mi
              cpu: "80m"
