apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:  blitzshare-event-worker-hpa
  namespace: blitzshare-ns
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blitzshare-event-worker-dpl
  targetCPUUtilizationPercentage: 50