// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Mq is an autogenerated mock type for the Mq type
type Mq struct {
	mock.Mock
}

// Sub provides a mock function with given fields: topic, cb
func (_m *Mq) Sub(topic string, cb func(*[]byte)) {
	_m.Called(topic, cb)
}
